variables:
  APPLICATION: "ams-vstore"
  REGISTRY: "docker-hub.2gis.ru"
  IMAGE: "ams/vstore"
  GIT_STRATEGY: none
  DEIS_CONTROLLER_PROD_N3: "http://deis.n3.nato/"
  DEIS_CONTROLLER_PROD_M1: "http://deis.m1.nato/"
  DEIS_CONTROLLER_PROD_D1: "http://deis.d1.nato/"
  DEIS_MEMORY_LIMITS_PROD_N3: "cmd=256M"
  DEIS_MEMORY_LIMITS_PROD_M1: "cmd=256M"
  DEIS_MEMORY_LIMITS_PROD_D1: "cmd=256M"
  DEIS_SCALE_PROD_N3: "cmd=1"
  DEIS_SCALE_PROD_M1: "cmd=1"
  DEIS_SCALE_PROD_D1: "cmd=1"

stages:
  - build:app
  - build:image
  - deploy

# ================= Build =================

build:app:
  variables:
    GIT_STRATEGY: clone
  image: $REGISTRY/microsoft/aspnetcore-build:1.1.0-projectjson
  stage: build:app
  environment: test
  script:
    - dotnet restore
    - dotnet publish VStore.Host/project.json -c release -o $(pwd)/publish/vstore
    - mkdir publish/vstore/.aws
    - INPUT=env/credentials.gpg OUTPUT=publish/vstore/.aws/credentials
    - echo $GPG_PASSWORD | gpg --output $OUTPUT --batch --no-tty --yes --passphrase-fd 0 --decrypt $INPUT
  tags:
    - 2gis
    - docker
  artifacts:
    name: "${APPLICATION}_${CI_BUILD_REF_NAME}"
    expire_in: '1 week'
    paths:
      - publish/vstore/

build:image:
  image: $REGISTRY/2gis/docker:1.11.2
  services:
    - docker:dind
  stage: build:image
  environment: test
  only:
    - master
    - /^release\/.*$/
  script:
    - REGISTRY=$REGISTRY IMAGE=$IMAGE TAG=$CI_BUILD_REF_NAME DOCKER_FILE=publish/vstore/Dockerfile DOCKER_BUILD_CONTEXT=publish/vstore make docker-build
    - REGISTRY=$REGISTRY IMAGE=$IMAGE TAG=$CI_BUILD_REF_NAME make docker-push
  tags:
    - 2gis
    - docker
  when: on_success

# ================ Deploy =================

deploy:staging:
  image: $REGISTRY/2gis/deis-client:1.13
  stage: deploy
  environment: staging
  when: manual
  script:
    - DEIS_PROFILE=staging DEIS_USERNAME=$DEIS_STAGE_USERNAME DEIS_TOKEN=$DEIS_STAGE_TOKEN make deis-config-create
    - make deis-create
    - make deis-config-push
    - REGISTRY=$REGISTRY IMAGE=$IMAGE TAG=$CI_BUILD_REF_NAME DEIS_ENV_FILE=env/staging.ini make deis-pull
    - make deis-scale
    - make deis-info
    - make deis-apps-check
  tags:
    - 2gis
    - docker

deploy:production-n3:
  image: $REGISTRY/2gis/deis-client:1.13
  stage: deploy
  environment: production
  when: manual
  only:
    - master
  script:
    - DEIS_PROFILE=production-n3 DEIS_CONTROLLER=$DEIS_CONTROLLER_PROD_N3 DEIS_USERNAME=$DEIS_PROD_N3_USERNAME DEIS_TOKEN=$DEIS_PROD_N3_TOKEN make deis-config-create
    - make deis-create
    - DEIS_MEMORY_LIMITS="${DEIS_MEMORY_LIMITS_PROD_N3}" make deis-memory-limits-set
    - make deis-config-push
    - REGISTRY=$REGISTRY IMAGE=$IMAGE TAG=${CI_BUILD_REF_NAME} DEIS_ENV_FILE=env/prod_n3.ini make deis-pull
    - DEIS_SCALE="${DEIS_SCALE_PROD_N3}" make deis-scale
    - make deis-info
    - make deis-apps-check
  tags:
    - 2gis
    - docker
