version: '2'

services:
  vstore.host:
    image: user/vstore.host${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ~/.aws:/root/.aws:ro
